# T_MedicalMember医患关系表
<table border="0" cellpadding="5" cellspacing="0" width="90%">
                <tr>
                    <td bgcolor="#FBFBFB">
                        <table cellspacing="0" cellpadding="5" border="1" width="100%" bordercolorlight="#D7D7E5" bordercolordark="#D3D8E0">
                            <tr bgcolor="#F0F0F0">
                                <td>序号</td>
                                <td>列名</td>
                                <td>数据类型</td>
                                <td>长度</td>
                                <td>小数位</td>
                                <td>标识</td>
                                <td>主键</td>
                                <td>外键</td>
                                <td>允许空</td>
                                <td>默认值</td>
                                <td>说明</td>
                            </tr>
                            <tr>
                                <td>1</td>
                                <td>MedicalMemberID</td>
                                <td>int</td>
                                <td>4</td>
                                <td>0</td>
                                <td>是</td>
                                <td>是</td>
                                <td>&nbsp;</td>
                                <td>否</td>
                                <td>&nbsp;</td>
                                <td align="left">&nbsp;</td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td>MedicalMemberGID</td>
                                <td>nvarchar</td>
                                <td>128</td>
                                <td>0</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>否</td>
                                <td>newid</td>
                                <td align="left">&nbsp;</td>
                            </tr>
                            <tr>
                                <td>3</td>
                                <td>PatientGID</td>
                                <td>nvarchar</td>
                                <td>128</td>
                                <td>0</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>否</td>
                                <td>&nbsp;</td>
                                <td align="left">&nbsp;</td>
                            </tr>
                            <tr>
                                <td>4</td>
                                <td>PatientMID</td>
                                <td>nvarchar</td>
                                <td>64</td>
                                <td>0</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>否</td>
                                <td>&nbsp;</td>
                                <td align="left">&nbsp;</td>
                            </tr>
                            <tr>
                                <td>5</td>
                                <td>Status</td>
                                <td>int</td>
                                <td>4</td>
                                <td>0</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>是</td>
                                <td>&nbsp;</td>
                                <td align="left">&nbsp;</td>
                            </tr>
                            <tr>
                                <td>6</td>
                                <td>DoctorGID</td>
                                <td>nvarchar</td>
                                <td>128</td>
                                <td>0</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>否</td>
                                <td>&nbsp;</td>
                                <td align="left">&nbsp;</td>
                            </tr>
                            <tr>
                                <td>7</td>
                                <td>DoctorMID</td>
                                <td>nvarchar</td>
                                <td>64</td>
                                <td>0</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>否</td>
                                <td>&nbsp;</td>
                                <td align="left">&nbsp;</td>
                            </tr>
                            <tr>
                                <td>8</td>
                                <td>ChatGroupID</td>
                                <td>nvarchar</td>
                                <td>128</td>
                                <td>0</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>是</td>
                                <td>&nbsp;</td>
                                <td align="left">&nbsp;</td>
                            </tr>
                            <tr>
                                <td>9</td>
                                <td>TeamID</td>
                                <td>nvarchar</td>
                                <td>128</td>
                                <td>0</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>是</td>
                                <td>&nbsp;</td>
                                <td align="left">&nbsp;</td>
                            </tr>
                            <tr>
                                <td>10</td>
                                <td>BedNum</td>
                                <td>nvarchar</td>
                                <td>128</td>
                                <td>0</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>是</td>
                                <td>&nbsp;</td>
                                <td align="left">&nbsp;</td>
                            </tr>
                            <tr>
                                <td>11</td>
                                <td>AdmissionTime</td>
                                <td>datetime</td>
                                <td>8</td>
                                <td>3</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>是</td>
                                <td>&nbsp;</td>
                                <td align="left">&nbsp;</td>
                            </tr>
                            <tr>
                                <td>12</td>
                                <td>DiagnosisResult</td>
                                <td>nvarchar</td>
                                <td>128</td>
                                <td>0</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>是</td>
                                <td>&nbsp;</td>
                                <td align="left">&nbsp;</td>
                            </tr>
                            <tr>
                                <td>13</td>
                                <td>RecoveryPlan</td>
                                <td>nvarchar</td>
                                <td>128</td>
                                <td>0</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>是</td>
                                <td>&nbsp;</td>
                                <td align="left">&nbsp;</td>
                            </tr>
                            <tr>
                                <td>14</td>
                                <td>RecoveryPlanTime</td>
                                <td>datetime</td>
                                <td>8</td>
                                <td>3</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>是</td>
                                <td>&nbsp;</td>
                                <td align="left">&nbsp;</td>
                            </tr>
                            <tr>
                                <td>15</td>
                                <td>CreateTime</td>
                                <td>datetime</td>
                                <td>8</td>
                                <td>3</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>是</td>
                                <td>&nbsp;</td>
                                <td align="left">&nbsp;</td>
                            </tr>
                            <tr>
                                <td>16</td>
                                <td>UpdateTime</td>
                                <td>datetime</td>
                                <td>8</td>
                                <td>3</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>是</td>
                                <td>&nbsp;</td>
                                <td align="left">&nbsp;</td>
                            </tr>
                            <tr>
                                <td>17</td>
                                <td>IsDel</td>
                                <td>int</td>
                                <td>4</td>
                                <td>0</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>是</td>
                                <td>&nbsp;</td>
                                <td align="left">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
